# Generated by Django 2.0.6 on 2018-06-28 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.CharField(default='', max_length=400)),
                ('result_ready', models.BooleanField(default=False)),
                ('h1', models.IntegerField(default=0)),
                ('h2', models.IntegerField(default=0)),
                ('h3', models.IntegerField(default=0)),
                ('a', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='link',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='dj_parser.Page'),
        ),
    ]
